cache: pip



language: python
dist: trusty
sudo: required
matrix:
  include:
    - os: linux
      dist: trusty
      python: 2.7
    - os: linux
      dist: trusty
      python: 3.5
    - os: linux
      dist: trusty
      python: 3.6
    - os: linux
      dist: xenial
      python: 3.7
    - os: linux
      dist: trusty
      python: pypy
    - os: linux
      dist: trusty
      python: pypy35


env:
    - DROPBOX_ACCESS_TOKEN=GiQj7BV19aAAAAAAAAAACAevudx3Rxyca3vKenwRV9suPJ2sWKw3Bm6rC9CpxDM2


install:
  - pip install -U pip setuptools wheel pytest-rerunfailures pytest
  - pip install .

script:
  - pytest -v --reruns 5  dropboxfs/tests/test_dropboxfs.py 

after_success:
  - coveralls
