cache: pip
language: python
dist: xenial
sudo: required
python:
- '2.7'
- '3.7'
- '3.8'
- 3.9-dev
- pypy
- pypy3.7
env:
  global:
    secure: pAO+qNQXwsGGFoLM642bszXQc42oDa+T9DYi2EKYNu07tNfy65D1y4DN8384er4i3UOj1Y6zXxWsEi0HKzDuxdwerb1aNarsF2YGMGlGgxoJSx0Lx4PHdiX7xLt0ttxRYhz1MPV0Lf/1tBHOBaeOPH4hcTI+0w5kQahu8dqGszAFtdD+ch2Kjlm1lBtHCZGq/NFTq9UFejSCt7ID7Hd69A5CZru7OhNO/kGQGQqSGAHAbP+EufRv7r2kkX+Oa+rxCzgfAhNXAnEBIN/xMGNcQBl2iDxkHm2H4ZkcVYo/cILdIOYdCtJijiu8a+/1omUfrOfoOW5FuArrSGwiHooCo0l57VwfDwkId8YfMWO3bBSr1ZThryLeHnuXxM9QfGvAENQvcrQ27tco3fLG7/BqmGatBWoBGM8/UQ+5KOi8D+UBQ9HPRbcqdVXzZKwKLEVTOPJeJYF1P1skIu+lyRKx3PGs1V4nAyPocMq5nyy4xpi7j01RlpJIXOkI26SvXgIR09cRoKhLVjOnVhSJUqw5kV7fxj2gADzaqvRgzPN657KT8oAn73XBJLmmx30iWO0gzEm504KWO9Av8bGjUNZPBJgDXKigtQh7y24S6ctXaRcXxYnbLvQ4j2QjTvpMffHGBRgSwkLzuBn4ZJg0x1nP+cvmeTDQCH3LwGJzLghd2/Y=
install:
- pip install -U pip setuptools wheel pytest-rerunfailures pytest
- pip install .
script:
- pytest -v --reruns 5  dropboxfs/tests/test_dropboxfs.py
after_success:
- coveralls
