cache: pip
language: python
dist: xenial
sudo: required
python:
  - '2.7'
  - '3.7'
  - '3.8'
  - '3.9-dev'
  - 'pypy'
  - 'pypy3.7'
env:
    - DROPBOX_ACCESS_TOKEN=GiQj7BV19aAAAAAAAAAACAevudx3Rxyca3vKenwRV9suPJ2sWKw3Bm6rC9CpxDM2


install:
  - pip install -U pip setuptools wheel pytest-rerunfailures pytest
  - pip install .

script:
  - pytest -v --reruns 5  dropboxfs/tests/test_dropboxfs.py

after_success:
  - coveralls
